name: calculator_modularization_data_starter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  shared_preferences: 2.2.2
  provider: 6.1.1

  calculator_modularization_presentation:
    path: presentation

dev_dependencies:
  flutter_lints: 3.0.1